#项目配置
cooc:
  version: 1.0.0

#tomcat 配置
server:
  # 服务端口
  port: 80
  #    servlet:
  # 项目contextPath
  #        context-path: /
  tomcat:
    # tomcat的URI编码
    #    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# 日志配置
logging:
  level:
    com.zhuoan: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug


spring:

  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    #登录用户名
    username: root
    password: root
    #执行语句用户名
  #    data-username: root
  #    data-password: root
  mvc:
    favicon:
      enabled: false
      #    static-path-pattern: /static/**
    #    pathmatch:
    #关闭后缀匹配 请求地址 index.*都匹配 index
  #        use-registered-suffix-pattern: true
  #redis配置
  redis:

    host: 127.0.0.1
    port: 6379
    password:
  #关闭模版引擎缓存
#  thymeleaf:
#    cache: false
#  groovy:
#    template:
#      cache: false
#  freemarker:
#    cache: false
#    view:
#      prefix: /
#      suffix: .html
#  resources:
#    static-locations: /static/**

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cooc.demo.mapper.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  #   #redis配置
  # PageHelper分页插件
  #pagehelper:
  #    helperDialect: mysql
  #    reasonable: true
  #    supportMethodsArguments: true
  #    params: count=countSql



  #使用springboot自带的activemq，所以注释了下面的activemq配置
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin